const expData = {
  data: [
    {
      id: "1",
      company: "Ismart Inter Global",
      period: "January 2024 - July 2024",
      role: "Contract - Frontend Developer",
      proLang: "Flutter",
      bgColor: "bg-gradient-to-r from-gray-500 via-black-500 to-white-500",
      photo: "/assets/img/scc-logo.svg",
      desc: "Developed and maintained high-performance, responsive web-based supply chain applications using Flutter.",
      urlDetail: "/experiences/ismart/scc",
    },
    {
      id: "2",
      company: "Altimeda Cipta Visitama",
      period: "April 2024 - June 2024",
      role: "Contract - Mobile Developer",
      proLang: "Flutter",
      bgColor: "bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500",
      photo: "/assets/img/pei-logo.png",
      urlDetail: "/experiences/altimeda/mobile-dev",
      desc: "Developing Post Energy Indonesia Mobile App for tracking fuel distribution, transaction record and monitoring the record on mobile app",
    },
    {
      id: "3",
      company: "Go Billiard",
      period: "June 2024 - September 2024",
      role: "Freelancer - Backend Developer",
      proLang: "Node.js",
      bgColor: "bg-white",
      photo: "/assets/img/gobill-logo.png",
      urlDetail: "/experiences/altimeda/be-dev",
      desc: "Developed RESTful APIs for a billiard booking platform with two user roles: admin and customer.",
    },
    {
      id: "4",
      company: "Altimeda Cipta Visitama",
      period: "July 2024 - Present",
      role: "Full Time - Backend Developer",
      proLang: "Node.js",
      bgColor: "bg-projectedai",
      photo: "/assets/img/projectedai-logo.png",
      urlDetail: "/experiences/altimeda/be-dev",
      desc: "Develop restful api for Generative AI project to support integration and improve Artificial intelligence answer based on the product function",
    },
    {
      id: "5",
      company: "Tately Nv",
      period: "June 2022 - August 2022",
      role: "Internship - Mobile Developer",
      proLang: "Flutter",
      bgColor: "bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500",
      photo: "/assets/img/hazob-logo.png",
      urlDetail: "/experiences/tatelynv",
      desc: "Develop the HAZOB app, a digitalization of the Hazard Observation Card that integrates with Google Spreadsheet API and Google Drive API.",
    },
    {
      id: "6",
      company: "Informatics Laboratory",
      period: "January 2024 - July 2024",
      role: "Practicum Assistant",
      proLang: "",
      bgColor: "bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500",
      photo: "/assets/img/iflab-logo.png",
      desc: "Assisted 10 students per practicum in Software Construction, Web Programming, and Mobile Programming, guiding them through 13 comprehensive modules. Evaluated their practical work to ensure a thorough understanding and application of key concepts.",
      urlDetail: "/experiences/ismart/fe",
    },
    {
      id: "7",
      company: "Telkom University",
      period: "April 2024 - June 2024",
      role: "Lecturer Assistant",
      proLang: "",
      bgColor: "bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500",
      photo: "/assets/img/telu-logo.png",
      urlDetail: "/experiences/altimeda/mobile-dev",
      desc: "Assisted in creating assignments and provided guidance for 30+ students in both Mobile and Web Programming courses.",
    },
  ],
};
const expData2 = {
  data: [
    {
      id: "1",
      company: "Informatics Laboratory",
      period: "January 2024 - July 2024",
      role: "Practicum Assistant",
      proLang: "",
      bgColor: "bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500",
      photo: "/assets/img/iflab-logo.png",
      desc: "I served as a practicum assistant for three courses: Web Programming (Codeigniter 3 and PHP), Software Construction (C#), and Mobile Programming (Flutter and Dart). In each course, I assisted 10 students in understanding key concepts like singleton and OOP, covered 13 topics, provided support with final assignments, and evaluated students' practical work.",
      urlDetail: "/experiences/ismart/fe",
    },
    {
      id: "2",
      company: "Telkom University",
      period: "April 2024 - June 2024",
      role: "Lecturer Assistant",
      proLang: "",
      bgColor: "bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500",
      photo: "/assets/img/telu-logo.png",
      urlDetail: "/experiences/altimeda/mobile-dev",
      desc: "Developed and maintained high-performance, responsive web-based supply chain applications using Flutter. Collaborated closely with backend teams to integrate seamless API communication, enhancing overall system efficiency. Consistently delivered tasks ahead of schedule, completing 16 key features that significantly improved functionality. Ensured full responsiveness across devices, providing an optimal user experience. Implemented Bloc state management, creating scalable and maintainable code. Continuously sought process improvements, adopting tools and techniques that boosted productivity and quality.",
    },
  ],
};
export { expData, expData2 };
