const expData = {
  data: [
    {
      id: "1",
      company: "Ismart Inter Global",
      period: "January 2024 - July 2024",
      role: "Contract - Frontend Developer",
      proLang: "Flutter",
      bgColor: "bg-gradient-to-r from-gray-500 via-black-500 to-white-500",
      photo: "/assets/img/scc/scc-logo.svg",
      desc: "Developed and maintained high-performance, responsive web-based supply chain applications using Flutter.",
      urlDetail: "/experiences/ismart/scc",
    },
    {
      id: "2",
      company: "Altimeda Cipta Visitama",
      period: "April 2024 - June 2024",
      role: "Contract - Mobile Developer",
      proLang: "Flutter",
      bgColor: "bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500",
      photo: "/assets/img/pei/pei-logo.png",
      urlDetail: "/experiences/altimeda/pei",
      desc: "Developing Post Energy Indonesia Mobile App for tracking fuel distribution, transaction record and monitoring the record on mobile app",
    },
    {
      id: "3",
      company: "Go Billiard",
      period: "June 2024 - September 2024",
      role: "Freelancer - Backend Developer",
      proLang: "Node.js",
      bgColor: "bg-white",
      photo: "/assets/img/gobill/gobill-logo.png",
      urlDetail: "/experiences/freelance/gobill",
      desc: "Developed RESTful APIs for a billiard booking platform with two user roles: admin and customer.",
    },
    {
      id: "4",
      company: "Altimeda Cipta Visitama",
      period: "July 2024 - Present",
      role: "Full Time - Backend Developer",
      proLang: "Node.js",
      bgColor: "bg-projectedai",
      photo: "/assets/img/projectedai/projectedai-logo.png",
      urlDetail: "/experiences/altimeda/be-dev",
      desc: "Develop restful api for Generative AI project to support integration and improve Artificial intelligence answer based on the product function",
    },
    {
      id: "5",
      company: "Tately Nv",
      period: "June 2022 - August 2022",
      role: "Internship - Mobile Developer",
      proLang: "Flutter",
      bgColor: "bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500",
      photo: "/assets/img/hazob/hazob-logo.png",
      urlDetail: "/experiences/tatelynv",
      desc: "Develop the HAZOB app, a digitalization of the Hazard Observation Card that integrates with Google Spreadsheet API and Google Drive API.",
    },
  ],
};
const expData2 = {
  data: [
    {
      id: "1",
      company: "Informatics Laboratory",
      period: "September 2022 - June 2023",
      role: "Practicum Assistant",
      proLang: "C#, Flutter, Codeigniter",
      bgColor: "bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500",
      photo: "/assets/img/iflab-logo.png",
      desc: "Assisted 10 students per practicum in Software Construction, Web Programming, and Mobile Programming, guiding them through 13 comprehensive modules. Evaluated their practical work to ensure a thorough understanding and application of key concepts.",
      urlDetail: "/experiences/ismart/fe",
    },
    {
      id: "2",
      company: "Telkom University",
      period: "November 2022 - June 2023",
      role: "Lecturer Assistant",
      proLang: "",
      bgColor: "bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500",
      photo: "/assets/img/telu-logo.png",
      urlDetail: "/experiences/altimeda/mobile-dev",
      desc: "Assisted in creating assignments and provided guidance for 30+ students in both Mobile and Web Programming courses.",
    },
    {
      id: "3",
      company: "Student Association of Software Engineering",
      period: "March 2022 - January 2023",
      role: "Head of Business Development Division",
      proLang: "",
      bgColor: "bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500",
      photo: "/assets/img/hmrpl-logo.png",
      urlDetail: "/experiences/altimeda/mobile-dev",
      desc: "Assisted in creating assignments and provided guidance for 30+ students in both Mobile and Web Programming courses.",
    },
    {
      id: "4",
      company: "Indonesian Young Entrepreneurs Association (HIPMI)",
      period: "January 2020 - January 2022",
      role: "Staff of Human Resource Department",
      proLang: "",
      bgColor: "bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500",
      photo: "/assets/img/hipmi-logo.png",
      urlDetail: "/experiences/altimeda/mobile-dev",
      desc: "As Executive Chairperson for Open Mind 2020 and Student Fair event, I led a core team of 9 members across 5 divisions, supervising the execution of 2 major programs. I also provided strategic solutions and analyses for program development and led the Open Mind 2021 initiative",
    },
  ],
};

const expForSlider = {
  data: [
    {
      id: "1",
      company: "Ismart Inter Global",
      period: "January 2024 - July 2024",
      role: "Contract - Frontend Developer",
      proLang: "Flutter",
      bgColor: "bg-gradient-to-r from-gray-500 via-black-500 to-white-500",
      photo: ["/assets/img/scc/scc-logo.svg"],
      desc: "Developed and maintained high-performance, responsive web-based supply chain applications using Flutter.",
      urlDetail: "/experiences/ismart/scc",
    },
    {
      id: "2",
      company: "Altimeda Cipta Visitama",
      period: "April 2024 - June 2024",
      role: "Contract - Mobile Developer",
      proLang: "Flutter",
      bgColor: "bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500",
      photo: [
        "/assets/img/pei/pei-logo.png",
        "/assets/img/pei/pei-1.jpg",
        "/assets/img/pei/pei-2.jpg",
      ],
      urlDetail: "/experiences/altimeda/pei",
      desc: "Developing Post Energy Indonesia Mobile App for tracking fuel distribution, transaction record and monitoring the record on mobile app",
    },
    {
      id: "3",
      company: "Go Billiard",
      period: "June 2024 - September 2024",
      role: "Freelancer - Backend Developer",
      proLang: "Node.js",
      bgColor: "bg-white",
      photo: ["/assets/img/gobill/gobill-logo.png"],
      urlDetail: "/experiences/freelance/gobill",
      desc: "Developed RESTful APIs for a billiard booking platform with two user roles: admin and customer.",
    },
    {
      id: "4",
      company: "Altimeda Cipta Visitama",
      period: "July 2024 - Present",
      role: "Full Time - Backend Developer",
      proLang: "Node.js",
      bgColor: "bg-projectedai",
      photo: ["/assets/img/projectedai/projectedai-logo.png"],
      urlDetail: "/experiences/altimeda/be-dev",
      desc: "Develop restful api for Generative AI project to support integration and improve Artificial intelligence answer based on the product function",
    },
    {
      id: "5",
      company: "Tately Nv",
      period: "June 2022 - August 2022",
      role: "Internship - Mobile Developer",
      proLang: "Flutter",
      bgColor: "bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500",
      photo: ["/assets/img/hazob/hazob-logo.png"],
      urlDetail: "/experiences/tatelynv",
      desc: "Develop the HAZOB app, a digitalization of the Hazard Observation Card that integrates with Google Spreadsheet API and Google Drive API.",
    },
  ],
};
export { expData, expData2, expForSlider };
