const expData = {
  data: [
    {
      id: "6",
      company: "Altimeda Cipta Visitama",
      period: "January 2025 - February 2025",
      role: "Full Time - Backend Developer",
      proLang: "Node.js (Typescript)",
      bgColor: "bg-saunders",
      photo: "/assets/img/saunders/saunders-logo.png",
      urlDetail: "/experiences/altimeda/saunders",
      desc: "Developed RESTful APIs For Web Forecasting that assists in market demand analysis and prediction using historical data.",
    },
    {
      id: "4",
      company: "Altimeda Cipta Visitama",
      period: "July 2024 - Present",
      role: "Full Time - Backend Developer",
      proLang: "Node.js",
      bgColor: "bg-projectedai",
      photo: "/assets/img/projectedai/projectedai-logo.png",
      urlDetail: "/experiences/altimeda/projectedai",
      desc: "Develop restful api for Generative AI project to support integration and improve Artificial intelligence answer based on the product function",
    },
    {
      id: "3",
      company: "Go Billiard",
      period: "June 2024 - September 2024",
      role: "Freelancer - Backend Developer",
      proLang: "Node.js",
      bgColor: "bg-white",
      photo: "/assets/img/gobill/gobill-logo.png",
      urlDetail: "/experiences/freelance/gobill",
      desc: "Developed RESTful APIs for a billiard booking platform with two user roles: admin and customer.",
    },
    {
      id: "2",
      company: "Altimeda Cipta Visitama",
      period: "April 2024 - June 2024",
      role: "Contract - Mobile Developer",
      proLang: "Flutter",
      bgColor: "bg-gradient-to-r from-gray-500 via-black-500 to-white-500",
      photo: "/assets/img/pei/pei-logo.png",
      urlDetail: "/experiences/altimeda/pei",
      desc: "Developing Post Energy Indonesia Mobile App for tracking fuel distribution, transaction record and monitoring the record on mobile app",
    },
    {
      id: "1",
      company: "Ismart Inter Global",
      period: "January 2024 - July 2024",
      role: "Contract - Frontend Developer",
      proLang: "Flutter",
      bgColor: "bg-gradient-to-r from-gray-500 via-black-500 to-white-500",
      photo: "/assets/img/scc/scc-logo.svg",
      desc: "Developed and maintained high-performance, responsive web-based supply chain applications using Flutter.",
      urlDetail: "/experiences/ismart/scc",
    },
    {
      id: "5",
      company: "Tately Nv",
      period: "June 2022 - August 2022",
      role: "Internship - Mobile Developer",
      proLang: "Flutter",
      bgColor: "bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500",
      photo: "/assets/img/hazob/hazob-logo.png",
      urlDetail: "/experiences/tatelynv",
      desc: "Develop the HAZOB app, a digitalization of the Hazard Observation Card that integrates with Google Spreadsheet API and Google Drive API.",
    },
  ],
};
const expData2 = {
  data: [
    {
      id: "2",
      company: "Telkom University",
      period: "November 2022 - June 2023",
      role: "Lecturer Assistant",
      proLang: "",
      bgColor: "bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500",
      photo: "/assets/img/telu-logo.png",
      urlDetail: "/experiences/altimeda/mobile-dev",
      desc: "Assisted in creating assignments and provided guidance for 30+ students in both Mobile and Web Programming courses.",
    },
    {
      id: "1",
      company: "Informatics Laboratory",
      period: "September 2022 - June 2023",
      role: "Practicum Assistant",
      proLang: "C#, Flutter, Codeigniter",
      bgColor: "bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500",
      photo: "/assets/img/iflab-logo.png",
      desc: "Assisted 10 students per practicum in Software Construction, Web Programming, and Mobile Programming, guiding them through 13 comprehensive modules. Evaluated their practical work to ensure a thorough understanding and application of key concepts.",
      urlDetail: "/experiences/ismart/fe",
    },
    {
      id: "3",
      company: "Student Association of Software Engineering",
      period: "March 2022 - January 2023",
      role: "Head of Business Development Division",
      proLang: "",
      bgColor: "bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500",
      photo: "/assets/img/hmrpl-logo.png",
      urlDetail: "/experiences/altimeda/mobile-dev",
      desc: "Assisted in creating assignments and provided guidance for 30+ students in both Mobile and Web Programming courses.",
    },
    {
      id: "4",
      company: "Indonesian Young Entrepreneurs Association (HIPMI)",
      period: "January 2020 - January 2022",
      role: "Staff of Human Resource Department",
      proLang: "",
      bgColor: "bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500",
      photo: "/assets/img/hipmi-logo.png",
      urlDetail: "/experiences/altimeda/mobile-dev",
      desc: "As Executive Chairperson for Open Mind 2020 and Student Fair event, I led a core team of 9 members across 5 divisions, supervising the execution of 2 major programs. I also provided strategic solutions and analyses for program development and led the Open Mind 2021 initiative",
    },
  ],
};

const sliderProjectedAI = {
  id: "1",
  company: "Altimeda Cipta Visitama",
  period: "July 2024 - Present",
  role: "Full Time - Backend Developer",
  proLang: "Node.js",
  bgColor: "bg-projectedai",
  photo: [
    "/assets/img/projectedai/projectedai-1.png",
    "/assets/img/projectedai/projectedai-2.png",
    "/assets/img/projectedai/projectedai-4.png",
    "/assets/img/projectedai/projectedai-3.png",
  ],
  urlDetail: "/experiences/altimeda/be-dev",
  desc: "Develop restful api for Generative AI project to support integration and improve Artificial intelligence answer based on the product function",
  descDetail: [
    "Developed RESTful APIs using Express.js for document processing (CVs, contracts, catalogs).",
    "Collaborated with AI engineers to align APIs with business requirements.",
    "Used cron jobs to automate various services, ensuring smooth operations.",
    "Implemented microservices architecture and CQRS pattern to optimize system scalability and efficiency.",
    "Utilized PostgreSQL for database management and high-performance querying.",
    "Built services to create and manage events in Outlook Calendar, enhancing system functionality.",
  ],
};
const sliderSCC = {
  id: "1",
  company: "Ismart Inter Global",
  period: "January 2024 - July 2024",
  role: "Contract - Frontend Developer",
  proLang: "Flutter",
  bgColor: "bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500",
  photo: ["/assets/img/scc/scc-2.png", "/assets/img/scc/scc-1.png"],
  desc: "Developed and maintained high-performance, responsive web-based supply chain applications using Flutter.",
  descDetail: [
    "Web-Based Supply Chain Projects: Developed and maintained complex web applications for supply chain management, utilizing the Flutter framework to ensure high performance and responsiveness across platforms.",
    "Collaboration with Backend Teams: Worked closely with backend developers to integrate APIs and backend services, ensuring seamless communication between the frontend and backend, resulting in robust and efficient web applications.",
    "Efficient Task Management: Consistently completed assigned tasks ahead of schedule, demonstrating strong time management skills and a commitment to delivering high-quality results under tight deadlines.",
    "Feature Development: Successfully delivered 16 key features within the product, significantly enhancing its functionality and user experience.",
    "Responsive Design: Achieved full responsiveness for the website across various screen sizes, ensuring an optimal user experience on all devices, from desktops to mobile phones.",
    "State Management with Bloc: Implemented Bloc state management in Flutter projects, leading to more maintainable, scalable, and testable code, which enhanced the overall stability and user experience of the applications.",
    "Continuous Improvement: Actively sought opportunities to improve the development process, including optimizing workflows and adopting new tools and technologies to enhance productivity and code quality.",
  ],
};
const sliderPei = {
  id: "3",
  company: "Tately Nv",
  period: "June - August 2022",
  role: "Contract - Mobile Developer",
  proLang: "Flutter",
  bgColor: "bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500",
  photo: [
    "/assets/img/pei/pei-1.jpg",
    "/assets/img/pei/pei-2.jpg",
    "/assets/img/pei/pei-3.jpg",
  ],
  urlDetail: "/experiences/tatelynv",
  desc: "Developing Post Energy Indonesia Mobile App for tracking fuel distribution, transaction record and monitoring the record on mobile app",
  descDetail: [
    "Migrated the existing mobile app to Flutter, enhancing performance and stability.",
    "Implemented Bloc state management, improving code maintainability and scalability.",
    "Optimized and maintained the existing product, ensuring smooth operation and user experience improvements.",
  ],
};
const sliderTatelyNv = {
  id: "5",
  company: "Tately Nv",
  period: "June 2022 - August 2022",
  role: "Internship - Mobile Developer",
  proLang: "Flutter",
  bgColor: "bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500",
  photo: ["/assets/img/hazob/hazob-2.png", "/assets/img/hazob/hazob-3.png"],
  urlDetail: "/experiences/tatelynv",
  desc: "Internship member for 3 months as IT support. Build Mobile Applications as digitalization of Hazard Observation Card. \n Responsibilities that included :",
  descDetail: [
    "Collaborated with the Head of the HSE (Health, Safety, Environment) Division.",
    "Successfully developed the HAZOB App, digitizing the hazard observation program at the company from a card-based system to a mobile application.",
    "Successfully implemented all 6 required functionalities within the Hazob App ",
    "Executed a 7-day user awareness campaign for the Hazob App, reaching over 10 employees at Tately NV.",
    "The application I created continues to be in use to this day.",
    "Technologies to build the application : ",
    "HAZOB App developed with flutter and dart",
    "HAZOB App is integrated Google Sheets API and Google Drive API.",
    "Github as version control.",
    "Database :",
    "Google spreadsheet used to storage the observations data and Google Drive used to storage the photos of the observation.",
    "Software Development Life Cycle :",
    "Implemented the prototype methodology within the Software Development Life Cycle.",
    ,
  ],
};
const sliderGobill = {
  id: "3",
  company: "Go Billiard",
  period: "June 2024 - September 2024",
  role: "Freelancer - Backend Developer",
  proLang: "Node.js",
  bgColor: "bg-white",
  urlDetail: "/experiences/freelance/gobill",
  photo: [
    "/assets/img/gobill/gobill-1.png",
    "/assets/img/gobill/gobill-2.png",
    "/assets/img/gobill/gobill-3.png",
    "/assets/img/gobill/gobill-4.png",
    "/assets/img/gobill/gobill-5.png",
    "/assets/img/gobill/gobill-6.png",
  ],
  desc: "Developed RESTful APIs for a billiard booking platform with two user roles: admin and customer.",
  descDetail: [
    "Developed RESTful APIs for a billiard booking platform with two user roles: admin and customer.",
    "Utilized Express.js and PostgreSQL to build scalable backend services and manage the database.",
    "Integrated Midtrans for seamless payment processing, enabling real-time booking transactions.",
    "Designed and implemented APIs for 6 services using the CQRS pattern, optimizing query and command separation for better system performance and maintainability.",
    "Secured the platform with JWT token authentication to ensure safe and reliable access control.",
    "Automated product availability updates using cron jobs to check-in and update the availability status of the products.",
  ],
};
const sliderSaunders = {
  id: "4",
  company: "Saunders",
  period: "January 2025 - February 2025",
  role: "Full Time - Backend Developer",
  proLang: "Node.js (Typescript)",
  bgColor: "bg-green-700",
  photo: [
    "/assets/img/saunders/saunders-1.png",
    "/assets/img/saunders/saunders-2.png",
    "/assets/img/saunders/saunders-3.png",
    "/assets/img/saunders/saunders-4.png",
    "/assets/img/saunders/saunders-5.png",
  ],
  urlDetail: "/experiences/saunders",
  desc: "Developed RESTful APIs For Web Forecasting that assists in market demand analysis and prediction using historical data.",
  descDetail: [
    "Developed 12 API endpoints in 1 week using Node.js, Express.js, and TypeScript",
    "Designed and implemented a database schema using TypeORM for structured data management",
    "Created entity models and relationships based on forecasting requirements",
    "Optimized data retrieval and processing using TypeORM query builde",
    "Mapped and retrieved data from fact tables and forecast records to ensure accurate reporting",
    "Implemented API endpoints for Forecast approval workflow,  Forecast data submission , Project listing, Monthly forecast retrieval and User-specific forecast views",
    "Enhanced API efficiency by optimizing queries and implementing proper indexing",
    "Ensured robust request validation and error handling",
    "Conducted API testing and debugging for reliability before deployment",
    "Collaborated with frontend developers for seamless integration",
  ],
};
export {
  expData,
  expData2,
  sliderProjectedAI,
  sliderPei,
  sliderTatelyNv,
  sliderSCC,
  sliderGobill,
  sliderSaunders,
};
